notes/noteapp/urls.py
from django.urls import path
from . import views

app_name = 'noteapp'

urlpatterns = [
    path('', views.main, name='main'),
    path('tag/', views.tag, name='tag'),
    path('note/', views.note, name='note'),
    path('notes_by_tag/<str:tag_name>/', views.notes_by_tag, name='notes_by_tag'),  
    path('detail/<int:note_id>', views.detail, name='detail'),
    path('done/<int:note_id>', views.set_done, name='set_done'),
    path('delete/<int:note_id>', views.delete_note, name='delete'),
]

notes/notes/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from noteapp.views import note, tag


urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('noteapp.urls')),
    path('users/', include('users.urls')),
    path('tag/', tag, name='tag'),
    path('note/', note, name='note'),
    path('quotes/', include('quotes.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

notes/quotes/urls.py
from django.urls import path
from . import views

app_name = 'quotes'

urlpatterns = [
    path('', views.main, name='main'),
    path('add_author/', views.add_author, name='add_author'),
    path('add_quote/', views.add_quote, name='add_quote'),
    path('author/', views.author, name='author'),
    path('quote/', views.quote, name='quote'),
    path('author_detail/<int:author_id>/', views.author_detail, name='author_detail'),
    path('quote_detail/<int:quote_id>/', views.quote_detail, name='quote_detail'),
]

notes/users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.signup_user, name='signup'),
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('profile/', views.profile, name='profile'),
]

notes/noteapp/models.py
from django.db import models
from django.contrib.auth.models import User


class Tag(models.Model):
    name = models.CharField(max_length=25, null=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=1)
    tags = models.ManyToManyField('self', blank=True)

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['user', 'name'], name='tag of username')
        ]

    def __str__(self):
        return f"{self.name}"


class Note(models.Model):
    name = models.CharField(max_length=50, null=False)
    description = models.CharField(max_length=150, null=False)
    done = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)
    tags = models.ManyToManyField(Tag)
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=1)

    def __str__(self):
        return f"{self.name}"

notes/noteapp/forms.py
from django import forms
from .models import Tag, Note
from django.forms import ModelForm, CharField, TextInput


class TagForm(ModelForm):

    name = forms.CharField(min_length=3, max_length=25, required=True, widget=TextInput())

    class Meta:
        model = Tag
        fields = ['name']


class NoteForm(ModelForm):

    name = CharField(min_length=5, max_length=50, required=True, widget=TextInput())
    description = CharField(min_length=10, max_length=150, required=True, widget=TextInput())

    class Meta:
        model = Note
        fields = ['name', 'description']
        exclude = ['tags']


class YourTagForm(ModelForm):
    name = forms.CharField(min_length=3, max_length=25, required=True, widget=TextInput())

    class Meta:
        model = Tag
        fields = ['name']

notes/noteapp/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from .models import Note, Tag
from .forms import NoteForm, TagForm, YourTagForm


def main(request):
    notes = Note.objects.filter(user=request.user).all() if request.user.is_authenticated else []
    return render(request, 'noteapp/index.html', {"notes": notes})


@login_required
def tag(request):
    form = YourTagForm(request.POST or None)  
    tag_name = None
    notes = None

    if request.method == 'POST' and form.is_valid():
        tag_name = form.cleaned_data['name']
        tag, created = Tag.objects.get_or_create(name=tag_name, user=request.user)

        if created:
            print(f"Nowy tag dodany: {tag_name}")

        notes = Note.objects.filter(tags=tag, user=request.user)

    return render(request, 'noteapp/tag.html', {'form': form, 'tag_name': tag_name, 'notes': notes})


@login_required
def note(request):
    tags = Tag.objects.filter(user=request.user).all()

    if request.method == 'POST':
        form = NoteForm(request.POST)
        if form.is_valid():
            new_note = form.save(commit=False)
            new_note.user = request.user
            new_note.save()
            choice_tags = Tag.objects.filter(name__in=request.POST.getlist('tags'), user=request.user)
            for tag in choice_tags.iterator():
                new_note.tags.add(tag)

            return redirect(to='noteapp:main')
        else:
            return render(request, 'noteapp/note.html', {"tags": tags, 'form': form})

    return render(request, 'noteapp/note.html', {"tags": tags, 'form': NoteForm()})


def notes_by_tag(request, tag_name):
    if tag_name:
        tag = Tag.objects.filter(name=tag_name, user=request.user).first()

        if tag:
            notes = Note.objects.filter(tags=tag, user=request.user)
            form = YourTagForm(initial={'name': tag_name})  # Initialize the form with the tag_name
            return render(request, 'noteapp/notes_by_tag.html', {'tag_name': tag_name, 'notes': notes, 'form': form})

    return redirect('noteapp:tag')


def notes_by_tag_page(request, tag_name):
    tag = Tag.objects.filter(name=tag_name, user=request.user).first()

    if tag:
        notes = Note.objects.filter(tags=tag, user=request.user)
        return render(request, 'noteapp/notes_by_tag.html', {'tag_name': tag_name, 'notes': notes})
    else:
        return redirect('noteapp:tag')


@login_required
def detail(request, note_id):
    note = get_object_or_404(Note, pk=note_id, user=request.user)
    return render(request, 'noteapp/detail.html', {"note": note})


@login_required
def set_done(request, note_id):
    Note.objects.filter(pk=note_id, user=request.user).update(done=True)
    return redirect(to='noteapp:main')


@login_required
def delete_note(request, note_id):
    Note.objects.get(pk=note_id, user=request.user).delete()
    return redirect(to='noteapp:main')

notes/noteapp/templates/noteapp/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Note information</title>
    <link
      rel="stylesheet"
      href="https://unpkg.com/@picocss/pico@latest/css/pico.min.css"
    />
    {% load static %}
    <link
      rel="stylesheet"
      href="{% static './noteapp/static/noteapp/modern.css' %}"
    />
    <link
      rel="stylesheet"
      href="{% static './noteapp/static/noteapp/style.css' %}"
    />
  </head>
  <body>
    <main class="container">
      <nav
        style="
          margin-bottom: 20px;
          border-bottom: 2px solid;
          padding-left: 30px;
        "
      >
        <ul>
          <li><a href="/" role="button"> Go back to the main page </a></li>
          <li>
            <a href="{% url 'quotes:quote' %}" role="button">Quotes List</a>
          </li>
          <li>
            <a href="{% url 'quotes:author' %}" role="button">Authors List</a>
          </li>
        </ul>
      </nav>
      {% block content %} {% endblock %}
    </main>
  </body>
</html>

notes/noteapp/templates/noteapp/detail.html
{% extends "noteapp/base.html" %} {% load extract_tags %} {% block content %}

<h1>{{note.name}}</h1>
<p>Description: <b>{{note.description}}</b></p>
<p>Time of creation: <kbd>{{note.created}}</kbd></p>
{% if note.done %}
<p>
  Status:
  <ins>Completed</ins>
</p>
{% else %}
<p>Status: <i>Not implemented</i></p>
{% endif %}
<p>Tags: <small> {{ note.tags|tags }} </small></p>
{% endblock %}

notes/noteapp/templates/noteapp/index.html
<!-- index.html -->
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Organizer</title>
    <link
      rel="stylesheet"
      href="https://unpkg.com/@picocss/pico@latest/css/pico.min.css"
    />
    {% load static %}
    <link
      rel="stylesheet"
      href="{% static './noteapp/static/noteapp/modern.css' %}"
    />
    <link
      rel="stylesheet"
      href="{% static './noteapp/static/noteapp/style.css' %}"
    />
  </head>
  <body>
    <main class="container">
      <nav
        style="
          margin-bottom: 20px;
          border-bottom: 2px solid;
          padding-left: 30px;
        "
      >
        {% if user.is_authenticated %}
        <ul>
          <li><a href="{% url 'noteapp:note' %}" role="button">Add note</a></li>
          <li><a href="{% url 'noteapp:tag' %}" role="button">Add Tag</a></li>
          <li>
            <a href="{% url 'quotes:quote' %}" role="button">Quotes List</a>
          </li>
          <li>
            <a href="{% url 'quotes:author' %}" role="button">Authors List</a>
          </li>
        </ul>
        <ul>
          <li>Welcome <b>{{ user.username }}!</b></li>
          <li><a href="{% url 'users:profile' %}" role="button">Profile</a></li>
          <li><a href="{% url 'users:logout' %}" role="button">Logout</a></li>
        </ul>
        {% else %}
        <ul>
          <li><a href="{% url 'users:signup' %}" role="button">Sign Up</a></li>
          <li><a href="{% url 'users:login' %}" role="button">Login</a></li>
          <li>
            <a href="{% url 'quotes:quote' %}" role="button">Quotes List</a>
          </li>
          <li>
            <a href="{% url 'quotes:author' %}" role="button">Authors List</a>
          </li>
        </ul>
        {% endif %}
      </nav>

      {% for note in notes %}
      <ul>
        <li>
          {% if not note.done %}
          <a
            href="{% url 'noteapp:detail' note.id %}"
            role="button"
            class="outline"
          >
            {{ note.name }}
          </a>
          <a href="{% url 'noteapp:set_done' note.id %}" role="button">
            Mark Done
          </a>
          <a
            href="{% url 'noteapp:delete' note.id %}"
            role="button"
            class="contrast"
          >
            Delete note
          </a>
          {% else %}
          <a
            href="{% url 'noteapp:detail' note.id %}"
            role="button"
            class="secondary"
            ><s>{{ note.name }}</s></a
          >
          {% endif %}
        </li>
      </ul>
      {% endfor %}
    </main>
  </body>
</html>

notes/noteapp/templates/noteapp/note.html
{% extends "noteapp/base.html" %} {% block content %}

<form method="POST" action="{% url 'noteapp:note' %}">
  {% csrf_token %}
  <div style="padding: 10px">
    <label> Note name: {{ form.name }} </label>
    <span>{{ form.errors.name }}</span>
  </div>
  <div style="padding: 10px">
    <label> Note description: {{ form.description }} </label>
    <span>{{ form.errors.description }}</span>
  </div>
  <div style="padding: 10px">
    <label>
      Select tags:
      <select name="tags" multiple="multiple" required>
        {% for tag in tags %}
        <option value="{{tag.name}}">{{tag.name}}</option>
        {% endfor %}
      </select>
    </label>
  </div>
  <div class="grid">
    <button type="submit">Submit</button>
    <button type="reset" class="secondary">Reset</button>
  </div>
</form>
{% endblock %}

notes/noteapp/templates/noteapp/notes_by_tag.html
{% extends "noteapp/base.html" %} {% block content %}

<form method="POST" action="{% url 'noteapp:tag' %}">
  {% csrf_token %}
  <div style="padding: 10px">
    <label for="id_name">Enter the tag name:</label>
    {{ form.name }}
    <span>{{ form.errors.name }}</span>
  </div>
  <div style="padding: 10px">
    <label for="id_tags">Select tags:</label>
    {{ form.tags }}
    <span>{{ form.errors.tags }}</span>
  </div>
  <div class="grid">
    <button type="submit">Submit</button>
    <button type="reset" class="secondary">Reset</button>
  </div>
</form>

{% if tag_name %}
<h2>Notes with Tag: {{ tag_name }}</h2>
<ul>
  {% for note in notes %}
  <li>{{ note.name }} - {{ note.description }}</li>
  {% endfor %}
</ul>
<a href="{% url 'noteapp:tag' %}"> Add Note </a>
{% endif %} {% endblock %}

notes/noteapp/templates/noteapp/tag.html
{% extends "noteapp/base.html" %} {% block content %}

<form method="POST" action="{% url 'noteapp:tag' %}">
  {% csrf_token %}
  <div style="padding: 10px">
    <label for="id_name">Enter the tag name:</label>
    {{ form.name }}
    <span>{{ form.errors.name }}</span>
  </div>
  <div class="grid">
    <button type="submit">Submit</button>
    <button type="reset" class="secondary">Reset</button>
  </div>
</form>

{% if tag_name %}
<h2>Notes with Tag: {{ tag_name }}</h2>
<ul>
  {% for note in notes %}
  <li>{{ note.name }} - {{ note.description }}</li>
  {% endfor %}
</ul>
<a href="{% url 'noteapp:notes_by_tag' tag_name=tag_name %}">
  Search for a Note by Tag
</a>
{% endif %} {% endblock %}