notes/notes/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from noteapp.views import note, tag


urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('noteapp.urls')),
    path('users/', include('users.urls')),
    path('tag/', tag, name='tag'),
    path('note/', note, name='note'),
    path('quotes/', include('quotes.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

notes/quotes/urls.py
from django.urls import path
from . import views

app_name = 'quotes'

urlpatterns = [
    path('', views.main, name='main'),
    path('add_author/', views.add_author, name='add_author'),
    path('add_quote/', views.add_quote, name='add_quote'),
    path('author/', views.author, name='author'),
    path('quote/', views.quote, name='quote'),
    path('author_detail/<int:author_id>/', views.author_detail, name='author_detail'),
    path('quote_detail/<int:quote_id>/', views.quote_detail, name='quote_detail'),
]

notes/quotes/models.py
from django.db import models
from users.models import Profile  

class Author(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField()
    image = models.ImageField(upload_to='author_images/', blank=True, null=True)

    def __str__(self):
        return self.name


class Quote(models.Model):
    text = models.TextField()
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    user_profile = models.ForeignKey(Profile, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.text[:20]}... - {self.author}'


class Tag(models.Model):
    name = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return self.name
	

notes/quotes/forms.py
from django import forms
from .models import Quote, Author

class QuoteForm(forms.ModelForm):
    class Meta:
        model = Quote
        fields = ['text', 'author']


class AuthorForm(forms.ModelForm):
    class Meta:
        model = Author
        fields = ['name', 'description', 'image']

    def __init__(self, *args, **kwargs):
        super(AuthorForm, self).__init__(*args, **kwargs)
        self.fields['image'].required = False

    def clean_description(self):
        description = self.cleaned_data.get('description')
        if not description:
            raise forms.ValidationError('This field is required.')
        return description

notes/quotes/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from .models import Author, Quote
from .forms import QuoteForm, AuthorForm


def main(request):
    authors = Author.objects.all()
    quotes = Quote.objects.all()
    return render(request, 'quotes/main.html', {'authors': authors, 'quotes': quotes})


def author(request):
    authors = Author.objects.all()
    return render(request, 'quotes/author.html', {'authors': authors})


def author_list(request):
    authors = Author.objects.all()
    return render(request, 'quotes/author_detail.html', {'author_id': author_id})


def author_detail(request, author_id):
    author = get_object_or_404(Author, pk=author_id)
    quotes = Quote.objects.filter(author=author)
    return render(request, 'quotes/author_detail.html', {'author': author, 'quotes': quotes})


@login_required
def add_author(request):
    if request.method == 'POST':
        form = AuthorForm(request.POST, request.FILES)
        if form.is_valid():
            author = form.save()
            return redirect('quotes:author_detail', author_id=author.pk)
    else:
        form = AuthorForm()
    return render(request, 'quotes/add_author.html', {'form': form})


def quote(request):
    quotes = Quote.objects.all()
    return render(request, 'quotes/quote.html', {'quotes': quotes})


def quote_list(request):
    quotes = Quote.objects.all()
    return render(request, 'quotes/quote.html', {'quotes': quotes})


def quote_detail(request, quote_id):
    quote = get_object_or_404(Quote, pk=quote_id)
    return render(request, 'quotes/quote_detail.html', {'quote': quote})


@login_required
def add_quote(request):
    if request.method == 'POST':
        form = QuoteForm(request.POST)
        if form.is_valid():
            quote = form.save(commit=False)
            quote.user_profile = request.user.profile
            quote.save()
            return redirect('quotes:quote_detail', quote_id=quote.pk)
    else:
        form = QuoteForm()
    return render(request, 'quotes/add_quote.html', {'form': form})

notes/quotes/templates/quotes/add_author.html
{% extends 'noteapp/base.html' %} {% block content %}
<h2>Add Author</h2>
<form method="post" enctype="multipart/form-data">
  {% csrf_token %} {{ form.as_p }}
  <button type="submit">Add</button>
</form>
{% endblock %}

notes/quotes/templates/quotes/add_quote.html
{% extends 'noteapp/base.html' %} {% block content %}
<h2>Add Quote</h2>
<form method="post">
  {% csrf_token %} {{ form.as_p }}
  <button type="submit">Add</button>
</form>
{% endblock %}

notes/quotes/templates/quotes/author.html
{% extends 'noteapp/base.html' %} {% block content %}
<h2>Authors</h2>
<ul>
  {% for single_author in authors %}
  <li>
    <a href="{% url 'quotes:author_detail' author_id=single_author.id %}">
      {{ single_author.name }}
    </a>
  </li>
  {% endfor %}
</ul>
{% if user.is_authenticated %}
<a href="{% url 'quotes:add_author' %}">Add New Author</a>
{% endif %} {% endblock %}

notes/quotes/templates/quotes/author_detail.html
{% extends 'noteapp/base.html' %} {% block content %}
<h2>{{ author.name }}</h2>
<p>{{ author.description }}</p>

{% if author.image %}
<img src="{{ author.image.url }}" alt="{{ author.name }} Image" />
{% endif %} {% if user.is_authenticated %}
<ul>
  <li>
    <a href="{% url 'quotes:add_author' %}" role="button">Add New Author</a>
  </li>
</ul>
{% endif %} {% endblock %}

notes/quotes/templates/quotes/quote.html
{% extends 'noteapp/base.html' %} {% block content %}
<h2>Quotes</h2>
<ul>
  {% for quote in quotes %}
  <li>
    <a href="{% url 'quotes:quote_detail' quote_id=quote.id %}"
      >{{ quote.text }}</a
    >
  </li>
  {% endfor %}
</ul>
{% if user.is_authenticated %}
<a href="{% url 'quotes:add_quote' %}">Add New Quote</a>
{% endif %} 
{% endblock %}

notes/quotes/templates/quotes/quote_detail.html
{% extends 'noteapp/base.html' %} {% block content %}
<h2>Quote</h2>
<p>{{ quote.text }}</p>
<p>Autor: {{ quote.author }}</p>
{% if user.is_authenticated %}
<ul>
  <li>
    <a href="{% url 'quotes:add_quote' %}" role="button">Add New Quote</a>
  </li>
</ul>
{% endif %} {% endblock %}